version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      # Using UV for faster dependency installation
    image: schemaforge-ai-service
    container_name: schemaforge-ai-service
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    networks:
      - schemaforge-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  schemaforge-ai-network:
    driver: bridge